version: '3.3'

services:
  file:
    image: file_service
    build: .
    volumes:
      - file_data:/usr/src/app/uploads
    env_file:
      - .env
    restart: unless-stopped

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - file
    ports:
      - 4050:4050

volumes:
  file_data:
  
networks:
  default:
    external:
      name: iodash-net
